<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FacultadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         DB::table('facultades')->insert([
            [
                'nombre' => 'Facultad de Agronomía',
                'direccion' => 'Av. Landaeta esquina Héroes del Acre., La Paz, Bolivia',
                'telefono' => null,
                'email' => null,
                'web' => 'https://fa.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/faumsabolivia/?locale=es_LA',
                'enlace_maps' => 'https://maps.app.goo.gl/H49HfKBtN1kFtLxy5',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Arquitectura, Artes, Diseño y Urbanismo',
                'direccion' => 'Edif. Simón Local D, Héroes del Acre 1734, La Paz',
                'telefono' => '2484818',
                'email' => null,
                'web' => 'http://faadu.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/p/Facultad-de-Arquitectura-Artes-Dise%C3%B1o-y-Urbanismo-UMSA-100064530109187/?locale=es_LA&_rdr',
                'enlace_maps' => 'https://maps.app.goo.gl/qyu9jkwYK15JijDp8',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Ciencias Económicas y Financieras',
                'direccion' => 'Zona 9, Av Ismael Montes 424, La Paz',
                'telefono' => '(591 - 2) 2441506',
                'email' => null,
                'web' => 'https://fcef.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/FCEF.UMSA/',
                'enlace_maps' => 'https://maps.app.goo.gl/uQq8HYT1exwGfZAq7',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Ciencias Farmacéuticas y Bioquímicas',
                'direccion' => 'Avenida Saavedra 2224, La Paz',
                'telefono' => '(591 - 2) 2441506',
                'email' => 'umsafacbiofar2021@gmail.com',
                'web' => 'https://farbio.edu.bo/bioquimica/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/FARBIO.UMSA',
                'enlace_maps' => 'https://maps.app.goo.gl/n8KL9CSgsNg4DgNHA',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Ciencias Puras y Naturales',
                'direccion' => 'Edificio viejo, La Paz',
                'telefono' => '22441570',
                'email' => null,
                'web' => 'https://www.fcpn.edu.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/fcpn.umsa',
                'enlace_maps' => 'https://maps.app.goo.gl/Xey2ZN57DdQgutHYA',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Ciencias Sociales',
                'direccion' => 'Federico Zuazo 1985, La Paz',
                'telefono' => '60141083',
                'email' => null,
                'web' => 'https://fcs.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/FacultadCienciasSocialesUMSA/',
                'enlace_maps' => 'https://maps.app.goo.gl/vN4e34BYdvBoSVA37',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Derecho y Ciencias Políticas',
                'direccion' => 'GV29+M28, Loayza, La Paz',
                'telefono' => '(591 - 2) 2441506',
                'email' => null,
                'web' => 'http://www.fdcp.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/p/Facultad-de-Derecho-y-Ciencias-Pol%C3%ADticas-UMSA-100067810272577/?locale=es_LA',
                'enlace_maps' => 'https://maps.app.goo.gl/Y4BDqvjGtVPSGCSL8',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Humanidades y Ciencias de la Educación',
                'direccion' => 'Av.6 de Agosto 2118, La Paz',
                'telefono' => '62533297',
                'email' => 'decanato.fhce@umsa.bo',
                'web' => 'https://fhce.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/HumanidadesUMSA/?locale=es_LA',
                'enlace_maps' => 'https://maps.app.goo.gl/npecX4iMdy6pm11S9',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Ingeniería',
                'direccion' => 'Plaza del Obelisco, Av. Camacho, La Paz',
                'telefono' => '2205000',
                'email' => 'facuingenieria2019@gmail.com',
                'web' => 'https://miing.umsa.edu.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/UMSA.Facultad.de.Ingenieria',
                'enlace_maps' => 'https://maps.app.goo.gl/xZ5xP7Uhp5m3aA14A',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Medicina, Enfermería, nutricion y Tecnología Médica',
                'direccion' => 'FVRJ+M22, Avenida Saavedra, La Paz',
                'telefono' => '73008433',
                'email' => 'carrera.medicina@umsalud.edu.bo',
                'web' => 'https://fment.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/fmentumsa',
                'enlace_maps' => 'https://maps.app.goo.gl/Hstqp5AXC5r3LqrVA',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Odontología',
                'direccion' => 'Av. Saavedra Nro. 2246, Zona Miraflores',
                'telefono' => '+591 2 2224447',
                'email' => null,
                'web' => 'https://fo.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/OdontologiaUMSA',
                'enlace_maps' => 'https://maps.app.goo.gl/1hzSF2Nrok18BpBh6',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Tecnología',
                'direccion' => 'Av. Arce No. 2295',
                'telefono' => '(591 - 2) 2442527',
                'email' => 'ftdecano@correo.umsa.bo',
                'web' => 'https://ft.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => 'https://www.facebook.com/facultad.tecnologia.umsa',
                'enlace_maps' => 'https://maps.app.goo.gl/3UsRkHQwWVKbuCLN9',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Facultad de Ciencias Geológicas',
                'direccion' => 'EDIFICIO HOY, PISO 6, Av. 6 de Agosto Nº 2170',
                'telefono' => '(591 2) 2442881',
                'email' => 'decfcg@umsa.bo',
                'web' => 'https://fcg.umsa.bo/',
                'logo' => null,
                'enlace_facebook' => null,
                'enlace_maps' => 'https://maps.app.goo.gl/sPafkYMfw4q1n4CZ9',
                'estado' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],




        ]);
    }
}